name: adaptive_navigation
description: A Flutter package providing adaptive switching between various navigation components.
version: 0.0.8
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/adaptive_navigation

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.2

dev_dependencies:
  cider: ^0.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
