blank_issues_enabled: false
contact_links:
  - name: File a bug report
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: File a feature request
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.