name: adaptive_breakpoints
description: A Flutter package providing Material Design breakpoints for responsive layouts.
version: 0.1.4
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/adaptive_breakpoints

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  cider: ^0.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
