name: adaptive_components
description: Implements Material Adaptive Components.
version: 0.0.1
homepage: https://github.com/material-components/material-components-flutter-adaptive

environment:
  sdk: ">=2.10.0-0.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints:
    # TODO: Return to normal.
    path: ../adaptive_breakpoints
  adaptive_navigation:
    # TODO: Return to normal.
    path: ../adaptive_navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
